#!/usr/bin/env node

let app = require('../app');
const debug = require('debug')('backend:server');
const http = require('http');

//get the port
const port = normalizePort(process.env.PORT || '4000');
app.set('port', port);

function normalizePort(val) {
    let port = parseInt(val, 10);
    
    if (port >= 0) {
        return port;
    } if (isNaN(port)) {
        return val;
    }
    return false;
};
//server http
const server = http.createServer(app);
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);


//event listener on http
function onListening() {
    var addr = server.address();
    var bind = typeof addr === 'string' ? 'pipe' + addr : 'port' + addr.port;
    debug('Listening on' + bind); 
};

//error event

function onError(error){
    if (error.syscall !== 'listen') {
        throw error;
      }

      console.log(error)
    
      var bind = typeof port === 'string'
        ? 'Pipe ' + port
        : 'Port ' + port;

        console.log(error)
    
      // handle specific listen errors with friendly messages
      switch (error.code) {
        case 'EACCES':
          console.error(bind + ' requires elevated privileges');
          process.exit(1);
          break;
        case 'EADDRINUSE':
          console.error(bind + ' is already in use');
          process.exit(1);
          break;
        default:
          throw error;
      }
};
