#!/usr/bin/env node

let app = require('../app');
const debug = require('debug')('backend:server');
const http = require('http');

//get the port
const port = normalizePort(process.env.PORT || '4000');
app.set('port', port);

//server http
const server = http.createServer(app);
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

function normalizePort(val) {
    let port = parseInt(val, 10);
    
    if (port >= 0) {
        return port;
    } if (isNaN(port)) {
        return val;
    }
    return false;
};

//event listener on http
function onListening() {
    var addr = server.address();
    var bind = typeof addr === 'string' ? 'pipe' + addr : 'port' + addr.port;
    debug('Listening on' + bind); 
};

//error event

function onError(error){
    if (error.syscall !== 'listen' ) {
        throw error;
    };
    var bind = typeof port === 'string' ? 'pipe' + port : 'port' + port;

    if (error.code === 'EACCES') {
        console.error(bind + 'You dont have permission for this port');
        process.exit(1);
    } else if(error.code === 'EADDRINUSE'){
        console.error(bind + 'Port Already Use');
        process.exit(1);
    } else {
        throw error;
    };
};
